hmcts/ccfr-fees-register-app

api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/BuildInfoIntegrationTest.java, api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/CategoriesIntegrationForCMCTest.java, api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/CategoriesIntegrationForDivorceTest.java, api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/CategoriesIntegrationForProbateTest.java, api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/Fees2APIFeeControllerTest.java, api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/Fees2APIToRetrieveTheCorrectFeeTest.java, api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/FunctionalTest.java, api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/IntegrationTestBase.java, api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/TestContextConfiguration.java, api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/dsl/FeesRegisterTestDsl.java, api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/dto/ChargeableFeeWrapperDto.java, api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/tokens/UserTokenFactory.java, api/src/functionalTest/resources/application-functional-tests.properties, api/src/test/java/uk/gov/hmcts/fees2/register/api/controllers/FeeControllerTest.java
This reverts commit 1b6102f255f7cdbe6092c75bbb1c5d1e5a882f51.
=> Revert "Revert "Pay 886 - migrated functional tests into the project""

api/src/main/java/uk/gov/hmcts/fees2/register/util/FeeLoader.java, api/src/main/resources/db/changelog/db.changelog-fees-managed-v5.yaml, api/src/main/resources/feeLoader.json, api/src/test/java/uk/gov/hmcts/fees2/register/api/repository/Fee2CrudComponentTest.java, api/src/test/java/uk/gov/hmcts/fees2/register/api/service/FeeVersionServiceTest.java, model/src/main/java/uk/gov/hmcts/fees2/register/data/repository/FeeVersionRepository.java, model/src/main/java/uk/gov/hmcts/fees2/register/data/service/FeeVersionService.java, model/src/main/java/uk/gov/hmcts/fees2/register/data/service/impl/FeeVersionServiceImpl.java
Reverts hmcts/ccfr-fees-register-app#114
=> Revert "Updated the missing fee data"

infrastructure/aat.tfvars
Reverts hmcts/ccfr-fees-register-app#142
=> Revert "sidam aat url"

infrastructure/aat.tfvars
This reverts commit b1cdf05e5955da6b9ec11ebe6c936aa974b00ede.
=> Revert "Point to SIDAM"

Jenkinsfile_parameterized
=> setting vault name

infrastructure/saat.tfvars
=> saat pointing to test tidam

api/build.gradle, api/src/main/java/uk/gov/hmcts/fees/register/api/configuration/SpringSecurityConfiguration.java, api/src/main/resources/application.properties, charts/fees-register-api/Chart.yaml, charts/fees-register-api/requirements.yaml, charts/fees-register-api/templates/NOTES.txt, charts/fees-register-api/values.template.yaml
Fees-register  helm chart  java upgrade etc
```
[ ] Yes
[x ] No
```
=> using health liveness and minor cleanup

infrastructure/saat.tfvars
Reverts hmcts/ccfr-fees-register-app#203
=> Revert "saat pointing to test tidam" ;  saat => sidam

api/src/main/resources/bootstrap.yaml, build.gradle, charts/fees-register-api/Chart.yaml, charts/fees-register-api/requirements.yaml, charts/fees-register-api/values.template.yaml, infrastructure/main.tf, infrastructure/variables.tf
changes to be able to build in AAT using flux
https://tools.hmcts.net/jira/browse/RPE-1009
Making postgress conditional
Upgrading java chart
Adding secret for DB password
```
[ ] Yes
[x] No
```
=> changes to be able to build in AAT using flux

infrastructure/aat.tfvars
=> AAT switched to SIDAM

api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/Fees2APIFeeControllerTest.java, api/src/main/java/uk/gov/hmcts/fees2/register/api/controllers/FeeController.java, api/src/main/resources/db/changelog/db.changelog-fees-managed-v6.yaml, api/src/main/resources/db/changelog/db.changelog-master.yaml, api/src/test/resources/application-embedded.properties, infrastructure/prod.tfvars
=> PAY-1590 Probate ranged fee from 0 to 5000 added

dependency-check-suppressions.xml
CVE-2018-1258 supression
```
[ ] Yes
[x ] No
```
=> CVE-2018-1258 supression

api/build.gradle, api/src/main/java/uk/gov/hmcts/fees2/register/api/controllers/FeeController.java, api/src/main/resources/application.properties, build.gradle, dependency-check-suppressions.xml, infrastructure/main.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/PAY-1607
Shared app insights 
```
[ ] Yes
[ x] No
```
=> Shared app insights

infrastructure/main.tf
Removed json appender using default one in java-logging
```
[ ] Yes
[x ] No
```
=> removed json appender using default

infrastructure/main.tf, infrastructure/state.tf
=> update ase name mechanisim

infrastructure/sprod.tfvars
sidam sprod
```
[ ] Yes
[ x] No
```
=> sidam sprod

infrastructure/main.tf
shared app_insights fix
```
[ ] Yes
[x ] No
```
=> shared app_insights fix

Dockerfile
curl is not part of that image anymore
```
[ ] Yes
[ ] No
```
=> fix heath check

infrastructure/demo.tfvars
=> Fee demo pointed to sidam aat

infrastructure/demo.tfvars
sidam demo
```
[ ] Yes
[x ] No
```
=> fees demo => sidam demo

infrastructure/main.tf
=> bumping azure provider version

api/src/main/java/uk/gov/hmcts/fees2/register/api/controllers/FeeController.java, api/src/test/java/uk/gov/hmcts/fees2/register/api/controllers/FeeControllerTest.java, api/src/test/java/uk/gov/hmcts/fees2/register/api/service/FeeSearchServiceTest.java, model/src/main/java/uk/gov/hmcts/fees2/register/data/dto/SearchFeeVersionDto.java, model/src/main/java/uk/gov/hmcts/fees2/register/data/service/impl/FeeSearchServiceImpl.java
https://tools.hmcts.net/jira/browse/PAY-1627
freg: discontinued fees - backend api
```
[ ] Yes
[x ] No
```
=> PAY-1627 - discontinued fees

README.md, api-contract/build.gradle, build.gradle, client/build.gradle, dependency-check-suppressions.xml, model/build.gradle
Updating readme to correct the information
```
[ ] Yes
[x] No
```
=> updating readme to correct the information

api-contract/src/main/java/uk/gov/hmcts/fees2/register/api/contract/FeeVersionStatusDto.java, api/src/main/java/uk/gov/hmcts/fees2/register/api/controllers/FeeController.java, api/src/main/resources/application.properties, api/src/test/java/uk/gov/hmcts/fees2/register/api/controllers/FeeControllerTest.java, api/src/test/java/uk/gov/hmcts/fees2/register/api/service/FeeSearchServiceTest.java, infrastructure/main.tf, model/src/main/java/uk/gov/hmcts/fees2/register/data/dto/SearchFeeVersionDto.java, model/src/main/java/uk/gov/hmcts/fees2/register/data/model/FeeVersionStatus.java, model/src/main/java/uk/gov/hmcts/fees2/register/data/service/impl/FeeSearchServiceImpl.java
=> PAY-1824 Duplicate fee codes issue fixed

api/src/main/resources/application.properties
updated application properties
```
[ ] Yes
[ ] No
```
=> Updated the application properties

build.gradle, client/build.gradle, dependency-check-suppressions.xml
=> Updated spring boot version

Dockerfile, Jenkinsfile_CNP, api/src/main/resources/application.properties, api/src/main/resources/bootstrap.yaml, charts/fees-register-api/Chart.yaml, charts/fees-register-api/requirements.yaml, charts/fees-register-api/values.aat.template.yaml, charts/fees-register-api/values.preview.template.yaml, charts/fees-register-api/values.yaml, dependency-check-suppressions.xml
=> PAY-2497:AKS Migration changes

infrastructure/main.tf
=> PAY-2497:Changed version from MOJ to CNP

Dockerfile, api/build.gradle, api/liquibase.gradle, build.gradle, dependency-check-suppressions.xml, infrastructure/main.tf
=> PAY-2497:Removing fee lookup API from API Gateway

.travis.yml, api/build.gradle, api/liquibase.gradle, build.gradle, client/build.gradle, dependency-check-suppressions.xml, infrastructure/main.tf, infrastructure/output.tf
=> PAY-2497:Aks related changes

charts/fees-register-api/Chart.yaml, charts/fees-register-api/values.yaml
=> Updated keyvault identity

Jenkinsfile_CNP
=> Enable Aks Migration flag

infrastructure/main.tf
=> PAY-2497:Updated resource name

charts/fees-register-api/Chart.yaml, charts/fees-register-api/requirements.yaml
Bumping charts version
```
[ ] Yes
[ ] No
```
=> Bumping charts version

charts/fees-register-api/values.yaml
=> PAY-2497:update spring password coming for key vault

infrastructure/main.tf
=> PAY-2497:Added functional test secrets to key vaults

Jenkinsfile_CNP
=>  legacy deployment on AAT

charts/fees-register-api/Chart.yaml, charts/fees-register-api/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/PAY-2612
Changes for upgrading chart version
```
[ ] Yes
[x] No
```
=> Changes for upgrading chart version

api/src/main/java/uk/gov/hmcts/fees/register/api/configuration/SwaggerConfiguration.java
No Ticket
Updating contact information in swagger 
```
[ ] Yes
[x] No
```
=> Updating contact information in swagger

Jenkinsfile_nightly, audit.json, security.sh
=> mutation tests

audit.json
=> Ignore security scan issue as its for API Specs

audit.json
End points are related to Api documentation and not functionalities , hence this can be suppressed for timebeing
```
[ ] Yes
[ ] No
```
=> PAY-2864-vulnerabilities suppression

Jenkinsfile_CNP, api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/Fees2APIFeeControllerTest.java, api/src/main/resources/feeLoader.json, charts/fees-register-api/Chart.yaml, charts/fees-register-api/values.preview.template.yaml, charts/fees-register-api/values.yaml, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/PAY-2913
PAY-2913 Fee Loader Issue
```
[ ] Yes
[x ] No
```
=> [[AR]] - PAY-2913 Fee Loader Issue

README.md, api/src/main/java/uk/gov/hmcts/fees/register/api/controllers/fees/FeesDtoMapper.java, api/src/main/resources/feeLoader.json, api/src/test/java/uk/gov/hmcts/fees/register/api/controllers/CategoryDtoMapperTest.java, api/src/test/java/uk/gov/hmcts/fees/register/api/controllers/FeesDtoMapperTest.java, api/src/test/java/uk/gov/hmcts/fees/register/api/controllers/RangeGroupsDtoMapperTest.java, build.gradle, charts/fees-register-api/Chart.yaml, charts/fees-register-api/values.preview.template.yaml, charts/fees-register-api/values.yaml, dependency-check-suppressions.xml, model/src/main/java/uk/gov/hmcts/fees/register/api/model/FixedFeeOld.java, model/src/test/java/uk/gov/hmcts/fees/register/api/model/RangeGroupTest.java
=> Pay 2953 nightly build fix

api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/Fees2APIFeeControllerTest.java, api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/dsl/FeesRegisterTestDsl.java
=> added keyword to fpl testcase

charts/fees-register-api/Chart.yaml, charts/fees-register-api/values.yaml
Chart changes
```
[ ] Yes
[x] No
```
=> PAY-2874-chart-changes

api/src/main/java/uk/gov/hmcts/fees2/register/api/controllers/FeeController.java, api/src/main/java/uk/gov/hmcts/fees2/register/util/SecurityUtils.java, dependency-check-suppressions.xml
=> PAY-3388- Adding author value changes in Demo

api/src/main/java/uk/gov/hmcts/fees2/register/api/controllers/FeeController.java
=> PAY-3388 - Modified log to cater null issues

dependency-check-suppressions.xml
=> PAY-3398 : Nightly Build Issue Fix

dependency-check-suppressions.xml
=> PAY-3432 : Nightly Build Issue Fix

dependency-check-suppressions.xml
=> PAY-3485 : Nightly Build Issue Fix

dependency-check-suppressions.xml
=> Nightly build issue fix

charts/fees-register-api/Chart.yaml, charts/fees-register-api/values.yaml, dependency-check-suppressions.xml
=> chart version publish for new instance pointing

dependency-check-suppressions.xml
=> PAY-3864 : Nightly Build issue fix

dependency-check-suppressions.xml, docker-compose.yml
=> Pay 3812 idam integration

infrastructure/main.tf
=> PAY-3917 : Removed the OLD DB instance mapping from main.tf

api-contract/build.gradle, api/build.gradle, build.gradle, client/build.gradle, cve-resolution-strategy.gradle, dependency-check-suppressions.xml, model/build.gradle
=> PAY-3962 Fee reg CVE fix

api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/CategoriesIntegrationForCMCTest.java, api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/Fees2APIFeeControllerTest.java, api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/dsl/FeesRegisterTestDsl.java
=> Modified Functional Tests

dependency-check-suppressions.xml
=> Pay-4085: Nightly Build issue Fix

audit.json
=> Pay-4115-Nightly Build issue fix

dependency-check-suppressions.xml
=> PAY-4179:Nightly Build issue fix

cve-resolution-strategy.gradle, dependency-check-suppressions.xml
=> removed CVE-2020-25638

api/src/main/java/uk/gov/hmcts/fees2/register/api/controllers/mapper/FeeDtoMapper.java, api/src/test/java/uk/gov/hmcts/fees2/register/api/controllers/FeeControllerTest.java, api/src/test/java/uk/gov/hmcts/fees2/register/api/service/FeeVersionServiceTest.java, model/src/main/java/uk/gov/hmcts/fees2/register/data/service/impl/FeeVersionServiceImpl.java, model/src/main/java/uk/gov/hmcts/fees2/register/data/util/FeesDateUtil.java
=> Valid To Date changes 3501

build.gradle
=> upgrade spring boot version for CVE-2021-22118

Jenkinsfile_CNP, security.sh
=> Fix nightly build issue

cve-resolution-strategy.gradle
=> resolved nightly build failure issue

build.gradle
=> resolved pact issue , apply patch

.gitignore, README.md, docker-compose.yml
=> removed keys

cve-resolution-strategy.gradle
=> CVE-2021-22096 fix

build.gradle
=> upgrade the log4j to 2.15.0

build.gradle
=> upgrade the log4j to 2.16.0

config/fortify-client.properties
=> new Fortify release id : 91387

build.gradle
=> upgrade the log4j to 2.17.0

api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/Fees2APIFeeControllerTest.java
=> Modified fucntional for discontinued fee

build.gradle, cve-resolution-strategy.gradle, dependency-check-suppressions.xml
…CVE-2022-23181
```
[ ] Yes
[ ] No
```
=> Fixed CVE issues

cve-resolution-strategy.gradle
=> Fixed CWE-862: Missing Authorization

charts/fees-register-api/Chart.yaml
…/chart-java/releases
```
[ ] Yes
[ ] No
```
=> Updated Java dependency version 

api/build.gradle, api/src/main/resources/feeLoader.json, cve-resolution-strategy.gradle, dependency-check-suppressions.xml
=> CVE issue 11042022

dependency-check-suppressions.xml
=> Suppressed CVE - CVE-2016-1000027

dependency-check-suppressions.xml, security.sh
=> Suppressed CVE - CVE-2022-22968

cve-resolution-strategy.gradle
=> CVE Fix - CVE-2022-29885

cve-resolution-strategy.gradle
=> Update tomcat version to compatible one

Jenkinsfile_nightly, dependency-check-suppressions.xml
=> Extend cve date to 30/09/2022 and disable night job for nightly branch

charts/fees-register-api/Chart.yaml, dependency-check-suppressions.xml
=> Fix for CVE-2022-34305

dependency-check-suppressions.xml
=> CVE-2022-31569 and CVE-2022-31548

Jenkinsfile_CNP, Jenkinsfile_nightly, api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/dsl/FeesRegisterTestDsl.java, api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/service/FeeService.java
https://tools.hmcts.net/jira/browse/PAY-3106
Update functional tests to use serenity rest assured.
```
[ ] Yes
[X] No
```
=> update func tests to serenity restassured

charts/fees-register-api/Chart.yaml, charts/fees-register-api/values.preview.template.yaml
=> PAY-5683 Java version upgrade in Chart yaml

charts/fees-register-api/values.preview.template.yaml
=> Fix fortify scan issue for username

dependency-check-suppressions.xml
=> Cve Fix- CVE-2022-25857

dependency-check-suppressions.xml
=> Cve suppressed - CVE-2022-38749, CVE-2022-38750, CVE-2022-38751

.gitignore, dependency-check-suppressions.xml
=> update date in suppression file

dependency-check-suppressions.xml
=> update suppression file

cve-resolution-strategy.gradle
=> upgrade tomcat embed version

dependency-check-suppressions.xml
=> suppressing postrges cve, no fix available

dependency-check-suppressions.xml
=> CVE Suppression Date Update

Jenkinsfile_CNP
=> Test pact verification changes

Jenkinsfile_CNP, Jenkinsfile_nightly, charts/fees-register-api/Chart.yaml
=> updated deprecated after to afterAlways

dependency-check-suppressions.xml
=> suppressing cve, no fix available

infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/PAY-4884
Remove deprecated terraform value.
```
[ ] Yes
[x] No
```
=> variable ilbIp no longer required

charts/fees-register-api/Chart.yaml, cve-resolution-strategy.gradle
=> upgrading java charts and commons fileupload to v1.5

dependency-check-suppressions.xml
=> suppressing new CVE

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/PAY-4884
Suppression for CVE with no fix available.
```
[ ] Yes
[x] No
```
=> Suppression for cve with no fix available.

dependency-check-suppressions.xml
=> surpression for spring

dependency-check-suppressions.xml
Supression of 2 CVE's
CVE-2023-2976
CVE-2022-1471
```
[ ] Yes
[X] No
```
=> CVE suppression nightly

dependency-check-suppressions.xml
CVE-2023-2976 and CVE-2022-1471 Suppression.
```
[ ] Yes
[X] No
```
=> CVE-2023-2976 and CVE-2022-1471 Suppression.

Jenkinsfile_CNP, Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/PAY-6400
Update slack mapping to fee-pay-nightly-pipeline.
```
[ ] Yes
[x] No
```
=> PAY-6400: Update new slack mapping

build.gradle
=> pact plugin upgrade to 4.6.1

api/build.gradle
https://tools.hmcts.net/jira/browse/PAY-6022
mutation tests are failing. need to upgrade pitest plugin.
```
[ ] Yes
[X] No
```
=> upgrade pitest to 1.9.0

dependency-check-suppressions.xml
https://github.com/hmcts/ccfr-fees-register-app/pull/new/PAY-6520
=> https://tools.hmcts.net/jira/browse/PAY-6520

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/PAY-6615
suppression of two tomcat vulnerabilities.
The proper fix is to upgrade spring boot, which we will need to do on the next round of upgrades.
- [ X] Does this PR introduce a breaking change
=> PAY-6651 CVE suppression

build.gradle
=> PAY-6571: Temp disable pact test

infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/PAY-6575
Add missing product name to allow access to DB.
=> PAY-6575: Add missing product name

infrastructure/sdp.tf
https://tools.hmcts.net/jira/browse/PAY-6683
SDP User setup for flrexible server db
=> PAY-6683 SDP user setup

charts/fees-register-api/Chart.yaml, infrastructure/main.tf
https://tools.hmcts.net/jira/browse/PAY-6701
Force access for flexible server tables
=> PAY-6701 Force access to tables

infrastructure/sdp.tf
https://tools.hmcts.net/jira/browse/PAY-6702
SDP access amended
=> PAY-6702 SDP access

dependency-check-suppressions.xml, infrastructure/main.tf, infrastructure/sdp.tf
https://tools.hmcts.net/jira/browse/PAY-6720
Fixed an SDP deployment in lower environments, fixed a secret mapping for v15. added some suppressions for CVEs which will be fixed in the next Springboot upgrade.
=> PAY-6720: Update to suppressions, sdp fix and secrets correction.

cve-resolution-strategy.gradle
https://tools.hmcts.net/jira/browse/PAY-6746
upgrade logback to address https://nvd.nist.gov/vuln/detail/CVE-2023-6481
=> PAY-6746 logback cve resolution

charts/fees-register-api/Chart.yaml, charts/fees-register-api/values.yaml, infrastructure/main.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/PAY-6659
Decommission v11 database
=> PAY-6659 Decommission v11 database

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/PAY-6872
Suppression
=> PAY-6872 CVE 2023-34042

cve-resolution-strategy.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/PAY-6974
cve suppression
- [X ] commit messages are meaningful and follow good commit message guidelines
=> PAY-6974 cve suppression

.github/workflows/stale.yml, charts/fees-register-api/Chart.yaml
https://tools.hmcts.net/jira/browse/PAY-6981
https://tools.hmcts.net/jira/browse/PAY-6982
Addition of stale.yml file for PR auto bit close and helm update
- [ x ] Does this PR introduce a breaking change
=> PAY-6982 Addition of stale.yml file for PR auto bit close and helm update

api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/Fees2APIFeeControllerTest.java, api/src/main/resources/feeLoader.json
https://tools.hmcts.net/jira/browse/PAY-7092
Functional tests needed to be changed to reflact fee amount updates
=> PAY-7092 fix for fees amount check in Functional tests

api/build.gradle, cve-resolution-strategy.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/PAY-6328
=> PAY-6328: Fix CVE-2022-1471

build.gradle, client/build.gradle, cve-resolution-strategy.gradle, dependency-check-suppressions.xml, gradle/wrapper/gradle-wrapper.properties
https://tools.hmcts.net/jira/browse/PAY-7124
PAY-7124: Address High Vulnerabilities and upgrade gradle
=> PAY-7124: Address High Vulnerabilities and upgrade gradle

build.gradle, cve-resolution-strategy.gradle
https://tools.hmcts.net/jira/browse/PAY-7141
Fix to Medium CVE vulnerabilities.
=> PAY-7141: Address Medium Vulnerabilities

build.gradle, jitpack.yml
https://tools.hmcts.net/jira/browse/PAY-7141
=> PAY-7141: Jitpack update

build.gradle
https://tools.hmcts.net/jira/browse/PAY-6863
re-enable pact verification
=> PAY-6863 re-enable pact verification

build.gradle
https://tools.hmcts.net/jira/browse/PAY-6863
This gradle change has been proven to work locally for pact verification
=> PAY-6863 changes to fix pact verification

build.gradle
Reverts hmcts/ccfr-fees-register-app#586
=> Revert "PAY-6863 changes to fix pact verification"

infrastructure/state.tf
https://tools.hmcts.net/jira/browse/CME-322
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
=> CME-322: Update azurerm

api/src/main/java/uk/gov/hmcts/fees2/register/api/controllers/mapper/FeeDtoMapper.java, api/src/test/java/uk/gov/hmcts/fees2/register/api/controllers/base/BaseTest.java, api/src/test/java/uk/gov/hmcts/fees2/register/api/controllers/mapper/FeeDtoMapperTest.java, model/src/main/java/uk/gov/hmcts/fees2/register/data/model/IdamUser.java
PAY-7517: Resolve problem  for users deleted by IDAM team
[PAY-7517] (https://tools.hmcts.net/jira/browse/PAY-7517).
=>  PAY-7517: Resolve problem  for users deleted by IDAM team

charts/fees-register-api/Chart.yaml
https://tools.hmcts.net/jira/browse/CME-423
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
=> CME-423: Oci image

api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/Fees2APIFeeControllerTest.java, api/src/main/resources/feeLoader.json
See [PAY-7704](https://tools.hmcts.net/jira/browse/PAY-7704)
Amended outcome of fee code amounts
Ran build.
=> PAY-7704 to fix functional tests

infrastructure/main.tf
See https://tools.hmcts.net/jira/browse/PAY-7766
removal of the azure.extension plpgsql
n/a
=> PAY-7766 removal of the azure.extension plpgsql

.github/workflows/ci.yml, api/build.gradle, build.gradle, jitpack.yml
https://tools.hmcts.net/jira/browse/CME-529
Replace jitpack with azure artifactory
=> CME-529 replace jitpack with azure artifactory

cve-resolution-strategy.gradle
https://tools.hmcts.net/jira/browse/PAY-7984
cve resolution
pipeline testing
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
* [X ] No
=> PAY-7984 commons-lang3 cve

cve-resolution-strategy.gradle
https://tools.hmcts.net/jira/browse/PAY-7984
uppgrade tomcat
pipeline
=> PAY-7940 tomcat cve

cve-resolution-strategy.gradle
https://tools.hmcts.net/jira/browse/PAY-8028
pipeline fixes
=> PAY-8028 tomcat cve

api/build.gradle
https://tools.hmcts.net/jira/browse/PAY-8145
Update postgresql library to resolve a vulnerability
FT should suffice.
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
=> PAY-8145: Update postgresql version
